import { Poppins, Oswald } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ['200','300','400','500','600','700'],
  display: 'swap',
  variable: "--font-poppins"
});

const oswald = Oswald({
  subsets: ['latin', 'latin-ext'],
  weight: ['200','300','400','500','600','700'],
  display: 'swap',
  variable: "--font-oswald"
});

export const metadata = {
  title: "Scizers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${oswald.variable}`}>{children}</body>
    </html>
  );
}